# Generated by Django 3.2 on 2021-07-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdeepApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='FamilySize',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
