# Generated by Django 3.2 on 2021-07-13 06:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IdeepApp', '0002_alter_clientdetails_familysize'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdate',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
